/** Declaration file generated by dts-gen */

export const error: number;

export function generate(input: any, opts: any, cb: any): void;

export function setErrorLevel(error: any): void;

export namespace generate {
    const prototype: {
    };

}

export namespace setErrorLevel {
    const prototype: {
    };

}

